# theme = "gruvbox_transparent"
theme = "base16_transparent"

[editor]
bufferline = "multiple"
default-yank-register = "+"
popup-border = "all"
gutters = ["diff"]
end-of-line-diagnostics = "disable"

[editor.lsp]
display-inlay-hints = false

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[keys.normal]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
ret = ":write"
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"
s = "goto_word"
# vim stuff
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
Y = ["save_selection", "select_all", "yank", "jump_backward"]
K = "hover"
q = ":quit"
Q = ":quit!"
S-ret = ":write!"

# vim muslce memory
[keys.select]
s = "goto_word"
0 = "goto_line_start"
"$" = "goto_line_end"

[keys.insert]
C-l = "completion"
