# theme = "gruvbox_transparent"
theme = "base16_transparent"

[editor]
bufferline = "multiple"
default-yank-register = "+"
popup-border = "all"
gutters = []
inline-completion-timeout = 150
end-of-line-diagnostics = "disable"

[editor.lsp]
display-inlay-hints = false
# inline-completion-auto-trigger = false
# Minimum severity to show a diagnostic after the end of a line:
# end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[keys.normal]
tab = ":sh zellij-picker open"
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
ret = ":write"
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"
s = "goto_word"
# vim stuff
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
K = "hover"
q = ":quit"
Q = ":quit!"
S-ret = ":write!"

# vim muslce memory
[keys.select]
s = "goto_word"
0 = "goto_line_start"
"$" = "goto_line_end"

[keys.insert]
tab = "inline_completion_accept"
# C-e = "inline_completion_dismiss"
# C-j = "inline_completion_next"
# C-k = "inline_completion_prev"
C-space = "inline_completion_trigger"
C-l = "completion"
